#!/bin/bash
# Usage:
# mongodb        <== start mongodb service for app
# mongodb stop   <== stop mongodb service for app

APP=${0##*/}
BASE=$(echo "${0%${APP}}../" | sed -e 's#^bin/../##g' -e 's#/bin/../#/#g')
source ${BASE}bin/conf.inc
source ${BASE}bin/func.inc

CMD="mongod --port ${MONGO_PORT}"
LOGFILE="${BASE}${LOGS_FOLDER}/mongodb.log"
DATA_FOLDER_FULL="${BASE}${DATA_FOLDER}"
EXIST=$(app_already_running ${CMD})
PARA=${1}
if [ "${PARA}" == "stop" ]; then
    if [ "${EXIST}" == "0" ]; then
        echo "[Ok] MongoDB already terminated."
    else
        PID=$(ps aux | grep "${CMD}" | grep -v grep | awk '{print $2}')
        kill -TERM ${PID}
        echo "[Ok] MongoDB stopped."
    fi
else
    if [ "${EXIST}" == "0" ]; then
        (${CMD} --dbpath ${DATA_FOLDER_FULL} --logpath ${LOGFILE} --logappend &)
        echo "[Ok] MongoDB started. Log write to ${LOGFILE}"
    else
        echo "[Ok] MongoDB already running. Log write to ${LOGFILE}"
    fi
fi
