#!/bin/bash
# Usage:
# redis        <== start redis service
# redis stop   <== stop redis service
# redis status <== show status of redis

APP=${0}
APP_NAME=${0##*/}
APP_PATH=${0%/${APP_NAME}}
if [ "${APP_PATH}" == "." ]; then
    APP_PATH="$(pwd)"
fi
SCRIPT_FOLDER=${APP_PATH##*/}  # Script's parent folder name
BASE=$(echo "${APP_PATH}/../" | sed -e "s#^${SCRIPT_FOLDER}/../##g" -e "s#/${SCRIPT_FOLDER}/../#/#g" -e "s#//#/#g")
source ${BASE}${SCRIPT_FOLDER}/conf.inc
source ${BASE}${SCRIPT_FOLDER}/func.inc

mkdir -p ${BASE}${LOGS_FOLDER}

PARA1=${1}
LOGFILE="${BASE}${LOGS_FOLDER}/redis.log"
touch ${LOGFILE}
CMD="redis-server --port ${REDIS_PORT}"
TAG="redis-server .*:${REDIS_PORT}"
EXIST=$(app_already_running ${TAG})
if [ "${PARA1}" = "stop" ]; then
    if [ "${EXIST}" = "0" ]; then
        echo "[Ok] Redis already terminated."
    else
        PID=$(ps aux | grep "${TAG}" | grep -v grep | awk '{print $2}')
        kill -TERM ${PID}
        echo "[Ok] Redis stopped."
    fi
elif [ "${PARA1}" = "status" ]; then
    if [ "${EXIST}" = "0" ]; then
        echo "[Ok] Redis NOT running."
    else
        echo "[Ok] Redis IS running."
    fi
else
    if [ "${EXIST}" = "0" ]; then
        (${CMD} >>${LOGFILE} 2>&1 &)
        echo "[Ok] Redis started. Log write to ${LOGFILE}"
    else
        echo "[Ok] Redis already running. Log write to ${LOGFILE}"
    fi
fi
