#!/bin/bash
# Usage:
# run       <== Run in frontend
# run start <== Run in background (daemon mode)
# run stop  <== Stop the daemon process

APP=${0##*/}
APP_PATH=${0%/${APP}}
if [ "${APP_PATH}" == "." ]; then
    APP_PATH="$(pwd)"
fi
SCRIPT_FOLDER=${APP_PATH##*/}  # Script's parent folder name
BASE=$(echo "${APP_PATH}/../" | sed -e "s#^${SCRIPT_FOLDER}/../##g" -e "s#/${SCRIPT_FOLDER}/../#/#g" -e "s#//#/#g")
source ${BASE}${SCRIPT_FOLDER}/conf.inc
source ${BASE}${SCRIPT_FOLDER}/func.inc

PARA=${1}
CMD="nodemon .* ${APP_TAG}"
EXIST=$(app_already_running "${CMD}")
if [ "${PARA}" == "stop" ]; then
    if [ "${EXIST}" == "0" ]; then
        echo "[Ok] App already terminated."
    else
        PID=$(ps aux | grep "${CMD}" | grep -v grep | awk '{print $2}')
        kill -TERM ${PID}
        echo "[Ok] App stopped."
    fi
    exit 0
fi

mkdir -p ${BASE}${LOGS_FOLDER}

echo "[Step] Installing dependency..."
NPM_LOG=${BASE}${LOGS_FOLDER}/npm.log
npm install >${NPM_LOG}
if [ "${?}" != "0" ]; then
    echo "[Error] Dependency install failed, please check ${NPM_LOG} for details."
    exit -1
else
    echo "[Ok] All dependecy installed."
fi

echo "[Step] Starting mongodb..."
EXIST=$(app_installed mongod)
if [ "${EXIST}" == "0" ]; then
    echo "[Error] Please install mongodb before run ${APP_TAG}!"
    exit -1
fi
${BASE}${SCRIPT_FOLDER}/mongodb

echo "[Step] Starting redis..."
EXIST=$(app_installed redis-server)
if [ "${EXIST}" == "0" ]; then
    echo "[Error] Please install redis before run ${APP_TAG}!"
    exit -1
fi
${BASE}${SCRIPT_FOLDER}/redis

echo "[Step] Start service..."
EXIST=$(app_installed nodemon)
if [ "${EXIST}" == "0" ]; then
    echo "[Error] Please install nodemon before run ${APP_TAG}!"
    exit -1
fi
APP_LOG=${BASE}${LOGS_FOLDER}/app.log
touch ${APP_LOG}
EXIST=$(app_already_running "${CMD}")
if [ "${PARA}" == "start" ]; then
    if [ "${EXIST}" != "0" ]; then
        echo "[Ok] App already running."
    else
        (nodemon ${BASE}${APP_ENTRY} ${APP_TAG} >>${APP_LOG} 2>&1 &)
        echo "[Ok] App started."
    fi
    echo "[Done] Please use \"tail -f ${APP_LOG}\" to follow the log file."
else
    if [ "${EXIST}" != "0" ]; then
        echo "[Info] App already running in background, please use \"${BASE}${SCRIPT_FOLDER}/run stop\" terminate it."
    else
        nodemon ${BASE}${APP_ENTRY}
    fi
fi
